[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "exciview"
version = "0.1.0"
description = "BSE Wavefunction Analysis Tools for FHI-aims"
authors = [
  { name="Ruiyi Zhou", email="ruiyi.zhou@phys.chem.ethz.ch" },
]
dependencies = [
  "numpy",
  "scipy",
  "ase",
]

[project.scripts]
exciview = "exciview.main:main"
